# Generated by Django 4.2.4 on 2023-08-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='type',
            field=models.IntegerField(choices=[(0, '通用'), (1, '系统'), (2, '功能'), (3, '模块')], default=0, verbose_name='功能类型分类'),
        ),
    ]
