# Generated by Django 4.2.5 on 2023-09-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_alter_tool_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServerApi',
            new_name='Server',
        ),
        migrations.AlterField(
            model_name='tool',
            name='type',
            field=models.IntegerField(choices=[(0, '通用'), (1, '系统'), (2, '功能'), (3, '模块')], default=0, help_text='对指令命令进行功能分类', verbose_name='类型分类'),
        ),
    ]
