# Generated by Django 4.2.5 on 2023-09-20 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_rename_serverapi_server_alter_tool_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeChoice',
            fields=[
                ('type', models.AutoField(primary_key=True, serialize=False, verbose_name='类型')),
                ('option', models.IntegerField(choices=[(0, '通用'), (1, '系统'), (2, '功能'), (3, '模块')], verbose_name='类型选项')),
                ('desc', models.CharField(max_length=200, verbose_name='分类描述')),
            ],
            options={
                'verbose_name': '测试分类',
                'verbose_name_plural': '分类列表',
            },
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'verbose_name': '服务器', 'verbose_name_plural': '服务器列表'},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'verbose_name': '测试功能', 'verbose_name_plural': '测试列表'},
        ),
        migrations.AlterField(
            model_name='server',
            name='host',
            field=models.GenericIPAddressField(protocol='IPv4', verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=200, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='server',
            name='port',
            field=models.IntegerField(default=3334, verbose_name='端口'),
        ),
        migrations.AlterField(
            model_name='server',
            name='sid',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='服务器'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='cmd',
            field=models.TextField(blank=True, help_text='测试指令代码', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(help_text='功能名称', max_length=200, verbose_name='功能'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='back.typechoice'),
        ),
    ]
