# Generated by Django 4.2.5 on 2023-09-20 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_typechoice_alter_server_options_alter_tool_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='type',
            field=models.ForeignKey(default=None, help_text='用于测试功能的区分和组合', on_delete=django.db.models.deletion.SET_DEFAULT, to='back.typechoice', verbose_name='分类'),
        ),
    ]
